import { Note, NoteColor } from './Notes.types';

export const NOTE_COLORS: { value: NoteColor; label: string; class: string; borderClass: string }[] = [
  { value: 'default', label: 'Default', class: 'bg-card', borderClass: 'border-border' },
  { value: 'red', label: 'Red', class: 'bg-red-100 dark:bg-red-950', borderClass: 'border-red-300 dark:border-red-800' },
  { value: 'orange', label: 'Orange', class: 'bg-orange-100 dark:bg-orange-950', borderClass: 'border-orange-300 dark:border-orange-800' },
  { value: 'yellow', label: 'Yellow', class: 'bg-yellow-100 dark:bg-yellow-950', borderClass: 'border-yellow-300 dark:border-yellow-800' },
  { value: 'green', label: 'Green', class: 'bg-green-100 dark:bg-green-950', borderClass: 'border-green-300 dark:border-green-800' },
  { value: 'teal', label: 'Teal', class: 'bg-teal-100 dark:bg-teal-950', borderClass: 'border-teal-300 dark:border-teal-800' },
  { value: 'blue', label: 'Blue', class: 'bg-blue-100 dark:bg-blue-950', borderClass: 'border-blue-300 dark:border-blue-800' },
  { value: 'purple', label: 'Purple', class: 'bg-purple-100 dark:bg-purple-950', borderClass: 'border-purple-300 dark:border-purple-800' },
  { value: 'pink', label: 'Pink', class: 'bg-pink-100 dark:bg-pink-950', borderClass: 'border-pink-300 dark:border-pink-800' },
  { value: 'gray', label: 'Gray', class: 'bg-gray-100 dark:bg-gray-950', borderClass: 'border-gray-300 dark:border-gray-800' },
];

export const SAMPLE_NOTES: Note[] = [
  {
    id: '1',
    title: 'Welcome to Notes!',
    content: 'This is your first note. You can add emojis, change colors, and organize with tags. Try pinning important notes or archiving old ones!',
    list: null,
    emoji: '👋',
    color: 'blue',
    tags: ['welcome', 'tutorial'],
    isPinned: true,
    status: 'active',
    createdAt: new Date('2025-11-01T10:00:00.000Z').getTime(),
    lastEditedAt: new Date('2025-11-01T10:00:00.000Z').getTime(),
    trashedAt: null,
  },
  {
    id: '2',
    title: 'Shopping List',
    content: '',
    list: ['Milk', 'Bread', 'Eggs', 'Butter', 'Cheese', 'Apples', 'Bananas'],
    emoji: '🛒',
    color: 'green',
    tags: ['shopping', 'groceries'],
    isPinned: true,
    status: 'active',
    createdAt: new Date('2025-11-02T09:30:00.000Z').getTime(),
    lastEditedAt: new Date('2025-11-03T14:20:00.000Z').getTime(),
    trashedAt: null,
  },
  {
    id: '3',
    title: 'Project Ideas',
    content: 'Build a task manager\nCreate a budgeting app\nDevelop a recipe organizer\nMake a travel planner',
    list: null,
    emoji: '💡',
    color: 'yellow',
    tags: ['ideas', 'projects'],
    isPinned: false,
    status: 'active',
    createdAt: new Date('2025-11-01T15:45:00.000Z').getTime(),
    lastEditedAt: new Date('2025-11-01T15:45:00.000Z').getTime(),
    trashedAt: null,
  },
  {
    id: '4',
    title: 'Meeting Notes',
    content: 'Discuss Q4 goals\nReview team performance\nPlan upcoming sprint\nAddress technical debt',
    list: null,
    emoji: '📝',
    color: 'purple',
    tags: ['work', 'meetings'],
    isPinned: false,
    status: 'active',
    createdAt: new Date('2025-10-28T11:00:00.000Z').getTime(),
    lastEditedAt: new Date('2025-10-28T11:30:00.000Z').getTime(),
    trashedAt: null,
  },
  {
    id: '5',
    title: 'Book Recommendations',
    content: 'Atomic Habits by James Clear\nThe Pragmatic Programmer\nDesigning Data-Intensive Applications\nClean Code by Robert Martin',
    list: null,
    emoji: '📚',
    color: 'teal',
    tags: ['books', 'reading'],
    isPinned: false,
    status: 'active',
    createdAt: new Date('2025-10-25T16:20:00.000Z').getTime(),
    lastEditedAt: new Date('2025-10-25T16:20:00.000Z').getTime(),
    trashedAt: null,
  },
  {
    id: '6',
    title: 'Workout Routine',
    content: 'Monday: Chest & Triceps\nWednesday: Back & Biceps\nFriday: Legs & Shoulders\nWeekend: Cardio',
    list: null,
    emoji: '💪',
    color: 'red',
    tags: ['fitness', 'health'],
    isPinned: false,
    status: 'archived',
    createdAt: new Date('2025-10-15T08:00:00.000Z').getTime(),
    lastEditedAt: new Date('2025-10-20T08:00:00.000Z').getTime(),
    trashedAt: null,
  },
  {
    id: '7',
    title: 'Old Draft',
    content: 'This note was moved to trash and will be automatically deleted after 30 days.',
    list: null,
    emoji: '🗑️',
    color: 'gray',
    tags: ['draft'],
    isPinned: false,
    status: 'trashed',
    createdAt: new Date('2025-10-01T12:00:00.000Z').getTime(),
    lastEditedAt: new Date('2025-10-01T12:00:00.000Z').getTime(),
    trashedAt: new Date('2025-10-20T12:00:00.000Z').getTime(),
  },
];
