import { CarPart } from './CarMaintenance.types';

// Common routine service types
export const ROUTINE_SERVICE_TYPES = [
  'Oil Change',
  'Tire Rotation',
  'Air Filter Replacement',
  'Cabin Air Filter Replacement',
  'Brake Inspection',
  'Brake Pad Replacement',
  'Battery Check',
  'Fluid Check',
  'Transmission Service',
  'Coolant Flush',
  'Wheel Alignment',
  'Tire Replacement',
  'Wiper Blade Replacement',
  'Spark Plug Replacement',
  'Belt Replacement',
] as const;

// Default internal car parts
export const DEFAULT_INTERNAL_PARTS: Omit<CarPart, 'id' | 'isCustom'>[] = [
  { name: 'Engine', category: 'internal' },
  { name: 'Transmission', category: 'internal' },
  { name: 'Oil Filter', category: 'internal' },
  { name: 'Air Filter', category: 'internal' },
  { name: 'Cabin Air Filter', category: 'internal' },
  { name: 'Fuel Filter', category: 'internal' },
  { name: 'Spark Plugs', category: 'internal' },
  { name: 'Battery', category: 'internal' },
  { name: 'Alternator', category: 'internal' },
  { name: 'Starter', category: 'internal' },
  { name: 'Radiator', category: 'internal' },
  { name: 'Coolant System', category: 'internal' },
  { name: 'Brake Pads', category: 'internal' },
  { name: 'Brake Rotors', category: 'internal' },
  { name: 'Brake Fluid', category: 'internal' },
  { name: 'Shock Absorbers', category: 'internal' },
  { name: 'Struts', category: 'internal' },
  { name: 'Suspension', category: 'internal' },
  { name: 'Exhaust System', category: 'internal' },
  { name: 'Catalytic Converter', category: 'internal' },
  { name: 'Timing Belt', category: 'internal' },
  { name: 'Serpentine Belt', category: 'internal' },
  { name: 'Water Pump', category: 'internal' },
  { name: 'Fuel Pump', category: 'internal' },
  { name: 'Fuel Injectors', category: 'internal' },
  { name: 'Ignition Coil', category: 'internal' },
  { name: 'Power Steering Fluid', category: 'internal' },
  { name: 'Transmission Fluid', category: 'internal' },
];

// Default external car parts
export const DEFAULT_EXTERNAL_PARTS: Omit<CarPart, 'id' | 'isCustom'>[] = [
  { name: 'Windshield', category: 'external' },
  { name: 'Front Bumper', category: 'external' },
  { name: 'Rear Bumper', category: 'external' },
  { name: 'Hood', category: 'external' },
  { name: 'Trunk/Tailgate', category: 'external' },
  { name: 'Front Driver Door', category: 'external' },
  { name: 'Front Passenger Door', category: 'external' },
  { name: 'Rear Driver Door', category: 'external' },
  { name: 'Rear Passenger Door', category: 'external' },
  { name: 'Driver Side Mirror', category: 'external' },
  { name: 'Passenger Side Mirror', category: 'external' },
  { name: 'Headlights', category: 'external' },
  { name: 'Tail Lights', category: 'external' },
  { name: 'Turn Signals', category: 'external' },
  { name: 'Front Tires', category: 'external' },
  { name: 'Rear Tires', category: 'external' },
  { name: 'Wheels/Rims', category: 'external' },
  { name: 'Roof', category: 'external' },
  { name: 'Sunroof/Moonroof', category: 'external' },
  { name: 'Wiper Blades', category: 'external' },
  { name: 'Side Windows', category: 'external' },
  { name: 'Rear Window', category: 'external' },
  { name: 'Paint/Body', category: 'external' },
  { name: 'License Plate', category: 'external' },
  { name: 'Antenna', category: 'external' },
];

// Keywords for auto-detection of car parts from service descriptions
export const PART_DETECTION_KEYWORDS: Record<string, string[]> = {
  'Engine': ['engine', 'motor'],
  'Oil Filter': ['oil', 'oil change', 'oil filter'],
  'Air Filter': ['air filter'],
  'Cabin Air Filter': ['cabin filter', 'cabin air'],
  'Fuel Filter': ['fuel filter'],
  'Spark Plugs': ['spark plug', 'sparkplug'],
  'Battery': ['battery'],
  'Alternator': ['alternator'],
  'Starter': ['starter'],
  'Radiator': ['radiator'],
  'Coolant System': ['coolant', 'antifreeze'],
  'Brake Pads': ['brake pad', 'brake', 'brakes'],
  'Brake Rotors': ['rotor', 'brake rotor'],
  'Brake Fluid': ['brake fluid'],
  'Shock Absorbers': ['shock', 'shock absorber'],
  'Struts': ['strut'],
  'Suspension': ['suspension'],
  'Exhaust System': ['exhaust', 'muffler'],
  'Catalytic Converter': ['catalytic', 'cat converter'],
  'Timing Belt': ['timing belt'],
  'Serpentine Belt': ['serpentine', 'belt'],
  'Water Pump': ['water pump'],
  'Fuel Pump': ['fuel pump'],
  'Fuel Injectors': ['injector', 'fuel injector'],
  'Transmission': ['transmission', 'trans'],
  'Transmission Fluid': ['transmission fluid', 'trans fluid'],
  'Windshield': ['windshield', 'wind shield'],
  'Front Bumper': ['front bumper'],
  'Rear Bumper': ['rear bumper', 'back bumper'],
  'Hood': ['hood'],
  'Driver Side Mirror': ['driver mirror', 'driver side mirror', 'left mirror'],
  'Passenger Side Mirror': ['passenger mirror', 'passenger side mirror', 'right mirror'],
  'Headlights': ['headlight', 'head light'],
  'Tail Lights': ['tail light', 'taillight'],
  'Turn Signals': ['turn signal', 'blinker'],
  'Front Tires': ['front tire', 'front tires'],
  'Rear Tires': ['rear tire', 'rear tires', 'back tire'],
  'Wiper Blades': ['wiper', 'wiper blade'],
  'Tire Rotation': ['tire', 'tires'],
  'Wheels/Rims': ['wheel', 'rim'],
};
