import { Recipe, RecipeType } from './RecipeBook.types';

export const RECIPE_TYPES: { value: RecipeType; label: string; emoji: string }[] = [
  { value: 'breakfast', label: 'Breakfast', emoji: '🍳' },
  { value: 'lunch', label: 'Lunch', emoji: '🥗' },
  { value: 'dinner', label: 'Dinner', emoji: '🍽️' },
  { value: 'snack', label: 'Snack', emoji: '🍿' },
  { value: 'dessert', label: 'Dessert', emoji: '🍰' },
  { value: 'appetizer', label: 'Appetizer', emoji: '🥟' },
  { value: 'beverage', label: 'Beverage', emoji: '🥤' },
];

export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: 'sample-1',
    name: 'Classic Pancakes',
    type: 'breakfast',
    description: 'Fluffy and delicious homemade pancakes perfect for weekend mornings.',
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    ingredients: [
      { id: 'i1', name: 'All-purpose flour', amount: '1.5', unit: 'cups' },
      { id: 'i2', name: 'Sugar', amount: '2', unit: 'tbsp' },
      { id: 'i3', name: 'Baking powder', amount: '2', unit: 'tsp' },
      { id: 'i4', name: 'Salt', amount: '0.5', unit: 'tsp' },
      { id: 'i5', name: 'Milk', amount: '1.25', unit: 'cups' },
      { id: 'i6', name: 'Egg', amount: '1', unit: 'large' },
      { id: 'i7', name: 'Butter', amount: '3', unit: 'tbsp' },
    ],
    instructions: [
      'In a large bowl, whisk together flour, sugar, baking powder, and salt.',
      'In another bowl, whisk together milk, egg, and melted butter.',
      'Pour wet ingredients into dry ingredients and mix until just combined (do not overmix).',
      'Heat a griddle or pan over medium heat and lightly grease.',
      'Pour 1/4 cup of batter for each pancake and cook until bubbles form on surface.',
      'Flip and cook until golden brown on the other side.',
      'Serve warm with maple syrup and butter.',
    ],
    tags: ['quick', 'easy', 'family-friendly'],
    imageUrl: null,
    dateAdded: '2025-01-15T00:00:00.000Z',
  },
  {
    id: 'sample-2',
    name: 'Quick Trail Mix',
    type: 'snack',
    description: 'A healthy and energizing snack mix perfect for on-the-go.',
    prepTime: 0,
    cookTime: 0,
    servings: 8,
    ingredients: [
      { id: 'i8', name: 'Mixed nuts', amount: '2', unit: 'cups' },
      { id: 'i9', name: 'Dried cranberries', amount: '1', unit: 'cup' },
      { id: 'i10', name: 'Dark chocolate chips', amount: '0.5', unit: 'cup' },
      { id: 'i11', name: 'Pumpkin seeds', amount: '0.5', unit: 'cup' },
    ],
    instructions: [
      'Combine all ingredients in a large bowl.',
      'Mix well to distribute ingredients evenly.',
      'Store in an airtight container for up to 2 weeks.',
    ],
    tags: ['no-cook', 'healthy', 'quick'],
    imageUrl: null,
    dateAdded: '2025-01-20T00:00:00.000Z',
  },
  {
    id: 'sample-3',
    name: 'Chocolate Chip Cookies',
    type: 'dessert',
    description: 'Chewy and chocolatey cookies that everyone loves.',
    prepTime: 15,
    cookTime: 12,
    servings: 24,
    ingredients: [
      { id: 'i12', name: 'Butter', amount: '1', unit: 'cup' },
      { id: 'i13', name: 'Brown sugar', amount: '1', unit: 'cup' },
      { id: 'i14', name: 'White sugar', amount: '0.5', unit: 'cup' },
      { id: 'i15', name: 'Eggs', amount: '2', unit: 'large' },
      { id: 'i16', name: 'Vanilla extract', amount: '2', unit: 'tsp' },
      { id: 'i17', name: 'All-purpose flour', amount: '2.75', unit: 'cups' },
      { id: 'i18', name: 'Baking soda', amount: '1', unit: 'tsp' },
      { id: 'i19', name: 'Salt', amount: '1', unit: 'tsp' },
      { id: 'i20', name: 'Chocolate chips', amount: '2', unit: 'cups' },
    ],
    instructions: [
      'Preheat oven to 375°F (190°C).',
      'Cream together butter and both sugars until fluffy.',
      'Beat in eggs and vanilla extract.',
      'In a separate bowl, combine flour, baking soda, and salt.',
      'Gradually mix dry ingredients into wet ingredients.',
      'Fold in chocolate chips.',
      'Drop rounded tablespoons of dough onto ungreased cookie sheets.',
      'Bake for 10-12 minutes until golden brown.',
      'Cool on baking sheet for 2 minutes before transferring to a wire rack.',
    ],
    tags: ['baking', 'classic', 'crowd-pleaser'],
    imageUrl: null,
    dateAdded: '2025-01-25T00:00:00.000Z',
  },
];
